[FIX] partner_summary.setdefault(nmpl.seller_id.name, []).append(nmpl) AttributeError: 'product.supplierinfo' object has no attribute 'name'
replace by product_name